## Source all files/functions in dannyverse
source("dannyverse/simulate_game.R")
source("dannyverse/simulate_spread.R")
source("dannyverse/simulate_total.R")
source("dannyverse/simulate_team_total.R")
source("dannyverse/get_mlb_season_scores.R")
source("dannyverse/get_mlb_daily_scores.R")
source("dannyverse/scrape_fangraphs.R")
source("dannyverse/get_probable_pitchers.R")
source("dannyverse/get_daily_rosters.R")
source("dannyverse/get_bovada_odds.R")
source("dannyverse/get_batting_order.R")
source("dannyverse/get_pitcher_game_logs.R")